name: conditionals-example

on: [push]

jobs:
  hello-conditionals:
    if: github.repository == 'Github-Actions'
    runs-on: ubuntu-latest
    steps:
      - name: "Hello Conditionals"
        run: echo "Hello Conditionals"
  
  goodbye-friday:
    runs-on: ubuntu-latest
    steps:
      - name: "Good bye Friday"
        run: echo "Good bye Friday"