name: Wrkflow-Commands

on:
  push: 
    branches: 
      - main

jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: Step 2 Group logging 
        run: |
          echo "::group:: Group Message"
          echo "Message 1"
          echo "Message 2"
          echo "::endgroup"

      - name: Step 2
        run: echo "MY_VALUE=hello" >> $Github_ENV

      - name: "Step 3"  
        run: echo $MY_VALUE

